# Generated by Django 3.2.8 on 2021-11-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('C', 'Completed'), ('F', 'In Progress')], max_length=128),
        ),
    ]
